name: "auxiliary"
description: "An auxiliary Dart library: classes, functions, constants, etc."
version: "0.0.1"
repository: "https://github.com/foodchaining/auxiliary-dart/tree/main/auxiliary"

environment:
  sdk: "^3.7.0"
resolution: "workspace"

dependencies:

dev_dependencies:
  lint:
  test:
