name: "auxiliary"
description: "An auxiliary Dart library: classes, functions, constants, etc."
version: "0.0.2"
repository: "https://github.com/foodchaining/auxiliary-dart/tree/main/auxiliary"

environment:
  sdk: "^3.7.0"
resolution: "workspace"

dependencies:
  async:
  collection:
  crypto:
  dartz:
  equatable:
  intl:
  logging:
  meta:
  nanoid:
  quiver:
  quiver_log:
  rxdart:
  stack_trace:
  synchronized:

dev_dependencies:
  lint:
  test:
